apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: mlflow-wine-prediction  # Container name updated with hyphens
  labels:
    app: mlflow-wine-prediction  # Labels should also use hyphens
spec:
  replicas: 1
  selector:
    app: mlflow-wine-prediction
    deploymentconfig: mlflow-wine-prediction
  template:
    metadata:
      labels:
        app: mlflow-wine-prediction
        deploymentconfig: mlflow-wine-prediction
    spec:
      containers:
      - name: mlflow-wine-prediction  # Container name updated with hyphens
        image: mlflow_wine_predict:latest
        envFrom:
          - configMapRef:
              name: my-configmap
        ports:
          - containerPort: 8080
